### ISSUE TITLE
TypeError: Cannot read property 'be' of undefined for NaN

### ISSUE THREAD

**Issue by vishalz** [vishalz/hello-js#6]
1) basic.30.operators.arithmetic.subtraction  v12 should be = NaN  and of type number :
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:57:28)

  2) basic.30.operators.arithmetic.multiplication  v22 should be = NaN and of type number:
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:118:28)

  3) basic.30.operators.arithmetic.multiplication  v24 should be = NaN and of type number:
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:130:28)

  4) basic.30.operators.arithmetic.remainder  v31 should be = NaN  and of type number:
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:176:28)

  5) basic.30.operators.arithmetic.unary-addition  v52 should be = hello , v53 should be = NaN:
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:270:28)

  6) basic.30.operators.arithmetic.bonus  v1005 should be = NaN, v1006 should be = NaN :
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:299:30)

  7) basic.30.operators.arithmetic.bonus  v1009 should be = NaN, v1010 should be = NaN :
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test/basic.30.operators.arithmetic.test.js:317:30)

**Comment by vishalz** [comment]
This is a should.js library compatibility issue. 
version  ^5.x.x supports chained assertions for NaN such as 
   obj.v12.should.be.NaN.and.be.of.type('number');

current version ^11 does not 

Solution: 
Break assertion into two statements 
 obj.v12.should.be.NaN;
 obj.v12.should.be.of.type('number');

**Comment by vishalz** [comment]
Fixed
